"""Generate docs/failure-gallery.md — one worked trace per diagnosis.

Runs deterministic, offline scenarios that each trigger a different failure mode,
and renders the decision trace so readers can see exactly how the verifier
diagnoses and the controller corrects. This is the teaching artifact: it makes
the architecture concrete.
"""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from srag import (  # noqa: E402
    Controller, CrossEncoderReranker, Embedder, EntailmentModel,
    GroundedGenerator, HybridRetriever, Planner, Stage1Pipeline, Verifier,
)
from srag.trace_view import render_trace_markdown  # noqa: E402

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def _sample_docs():
    with open(os.path.join(HERE, "data", "sample_corpus.jsonl")) as f:
        return [json.loads(l) for l in f if l.strip()]


def _controller(docs, generator=None, max_corrections=3):
    pipe = Stage1Pipeline(
        retriever=HybridRetriever(Embedder(prefer_fallback=True)),
        reranker=CrossEncoderReranker(prefer_fallback=True),
        generator=generator or GroundedGenerator(),
        planner=Planner(),
    ).index_documents(docs)
    return Controller(pipe, Verifier(EntailmentModel(prefer_fallback=True)),
                      tau=0.55, max_corrections=max_corrections)


def scenario_pass():
    ctrl = _controller(_sample_docs())
    return ("`pass` — a clean single-hop answer",
            "Retrieval is strong, the claim is entailed by its cited chunk, so the "
            "verifier passes on the first try and no correction fires.",
            ctrl.run("Who directed Seven Samurai?"))


def scenario_planning():
    ctrl = _controller(_sample_docs())
    return ("`planning_fault` → fill-and-retrieve — a bridge question",
            "The planner exposes a second hop whose phrasing depends on the first "
            "hop's answer. Coverage flags it; the controller fills the hop from the "
            "resolved entity, re-retrieves, and answers.",
            ctrl.run("What nationality is the director of the film Ran?"))


def scenario_retrieval():
    ctrl = _controller(_sample_docs())
    return ("`retrieval_fault` → abstain — nothing on-topic in the corpus",
            "No passage supports the question. Escalating re-retrieval surfaces "
            "nothing new, so the loop stops and the system abstains instead of "
            "hallucinating.",
            ctrl.run("What is the capital of France?"))


def scenario_conflict():
    docs = [
        {"id": "old", "source": "Old survey", "timestamp": "2018-01-01",
         "text": "The Aurora Bridge has a main span of 300 meters across the bay."},
        {"id": "new", "source": "New survey", "timestamp": "2024-01-01",
         "text": "The Aurora Bridge does not have a main span of 300 meters; it spans 450 meters across the bay."},
    ]
    ctrl = _controller(docs, max_corrections=2)
    return ("`conflict` → resolve by recency — contradictory sources",
            "Two high-scoring chunks disagree on the span. The verifier flags a "
            "conflict; the controller resolves it by recency and notes the "
            "discrepancy.",
            ctrl.run("What is the main span of the Aurora Bridge?"))


def scenario_generation():
    docs = [
        {"id": "ozu", "source": "Yasujiro Ozu",
         "text": "Yasujiro Ozu was a Japanese film director. His film Tokyo Story is acclaimed."},
    ]
    def oracle(question, evidence):
        # Fabricates a fact absent from the evidence, cited to the Ozu chunk.
        cid = next((c.id for c in evidence if "ozu" in c.id), None)
        return {"answer": "Gold Medal",
                "claims": [{"text": "Yasujiro Ozu won a Gold Medal at the 1960 Olympics",
                            "citations": [cid] if cid else []}],
                "unsupported_facts": [], "answerable": True}
    ctrl = _controller(docs, generator=GroundedGenerator(llm=oracle), max_corrections=2)
    return ("`generation_fault` — a fabricated claim caught by faithfulness",
            "The generator asserts a fact the cited chunk does not entail. The "
            "claim-level NLI check catches it (faithfulness < 1.0), so the system "
            "does not answer confidently.",
            ctrl.run("What Olympic medal did Yasujiro Ozu win in 1960?"))


def main():
    scenarios = [scenario_pass, scenario_planning, scenario_retrieval,
                 scenario_conflict, scenario_generation]
    out = ["# Failure-mode gallery\n",
           "One worked example per diagnosis, generated by `tools/make_gallery.py` "
           "on the deterministic offline stack (so it reproduces exactly). Each "
           "shows how the verifier *diagnoses* and the controller applies a "
           "*targeted* correction — the core idea of the architecture.\n",
           "> Regenerate: `python tools/make_gallery.py`\n"]
    for fn in scenarios:
        title, desc, state = fn()
        out.append(f"\n## {title}\n")
        out.append(desc + "\n")
        out.append(render_trace_markdown(state))
        out.append("\n---")
    path = os.path.join(HERE, "docs", "failure-gallery.md")
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(out) + "\n")
    print("wrote", os.path.relpath(path, HERE))


if __name__ == "__main__":
    main()
